from enum import Enum


class ViewPage(Enum):

    QUOTES = 0
    QUOTE_ENTRY = 1

    PRODUCTS = 2
    PRODUCT_ENTRY = 3
    PRODUCT_RATE_ENTRY = 4

    RATE_TYPES = 5
    RATE_TYPE_ENTRY = 6

    VEHICLE_COMBINATIONS = 7
    VEHICLE_COMBINATION_ENTRY = 8
