from enum import Enum


class ViewPage(Enum):

    QUOTES = 0
    QUOTE_ENTRY = 1
    QUOTE_ITEM_ENTRY = 2

    PRODUCTS = 3
    PRODUCT_ENTRY = 4
    PRODUCT_RATE_ENTRY = 5

    RATE_TYPES = 6
    RATE_TYPE_ENTRY = 7

    VEHICLE_COMBINATIONS = 8
    VEHICLE_COMBINATION_ENTRY = 9
